# Generated by Django 5.0.1 on 2024-05-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='about_me',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='user_images',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/user_images'),
        ),
        migrations.AddField(
            model_name='posts',
            name='short_description',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='tg_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
