# Generated by Django 5.0.1 on 2024-04-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_posts_short_description_alter_authors_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
